### ISSUE TITLE
Java Edition

### ISSUE THREAD

**Issue by limit123123** [ed-jones/csci318-group-project#2]
Can you write a java version??

**Comment by edjonesdev** [comment]
Sorry, this project was just something I did for university a few years ago so I'm done developing it. The source code is all freely available for you to inspect if you wanted to create your own Java port though :)

**Comment by limit123123** [comment]
Can we contact.with wechat?



---Original---
From: "Ed ***@***.***&gt;
Date: Wed, Apr 20, 2022 12:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ed-jones/adaptive-vs-random-testing] Java Edition (Issue #2)




 
Sorry, this project was just something I did for university a few years ago so I'm done developing it. The source code is all freely available for you to inspect if you wanted to create your own Java port though :)

**Comment by edjonesdev** [comment]
If you have any questions about the project please use the Discussions feature on GitHub :)
