### ISSUE TITLE
看不懂

### ISSUE THREAD

**Issue by limit123123** [ed-jones/csci318-group-project#3]

**Comment by edjonesdev** [comment]
Sorry I can only read English. I'm no longer maintaining this project, but if you have any questions I'll happily do my best to answer them.

**Comment by limit123123** [comment]
Thank you very much .Hello, can we communicate on wechat




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ed-jones/adaptive-vs-random-testing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月20日(星期三) 中午12:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ed-jones/adaptive-vs-random-testing] 看不懂 (Issue #3)





 
Sorry I can only read English. I'm no longer maintaining this project, but if you have any questions I'll happily do my best to answer them.
